name: Tests

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    name: pytest ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"
      - uses: Gr1N/setup-poetry@v8
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - run: poetry install --with=dev

      - name: Run tests
        shell: bash
        run: |
          PYTHONPATH="$(pwd)" poetry run pytest -vs --cov=matrixzulipbridge --cov-report term-missing
